teach_in_device:
  name: Teach-In Device
  description: Start the Teach-In-Process between the dongle and a device. During the teach-in normal packets are ignored
  fields:
    teach_in_time:
      name: Teach-In time
      description:
        "How long shall the teach-in process be active (in seconds) (max: 600). During the process no
        other packets get processed!"
      required: false
      advanced: false
      example: 60
      default: 60

    base_id:
      name: Used Base ID for this device for BS4-based teach-in
      description:
        "A communicator can use up to 128 different Base ID values within the allowed
        range of the start Base ID. If nothing is specified, the default Base ID will
        be used when communicating over 4BS. This ID has to be within the range of your transceiver."
      required: false
      advanced: true
      example: 01BEEF23
      default: ""
reset_rlc:
  name: Reset secure RLC
  description: Reset secure RLC to defined value
  target:
    entity:
      integration: enocean
      domain: climate
  fields:
    rlc:
      name: RLC
      description: RLC to set